### ISSUE TITLE
How to use pc-lint.vim?

### ISSUE THREAD

**Issue by SalahuddinAsh** [craigemery/dotFiles#12]
Hi, 
I'd like to integrate PC-Lint with VIM to be able to navigate to the warnings locations in the code easily. 
Could someone please explain how to use the "pc-lint.vim" file found in vim/compiler?
Thanks

**Comment by craigemery** [comment]
I'd use syntastic instead.
https://github.com/vim-syntastic/syntastic
It's what I use now.
